"""The lilx application icon, built from the project's ``logo.png``.

``logo.png`` in the project root is the only source of the icon. It is found
relative to this package (running from source) or next to the frozen executable's
data (PyInstaller, see ``packaging/lilx.spec``); no absolute paths are involved.

Qt then shows the icon everywhere it can at runtime: window icons, the macOS Dock and
Cmd+Tab, the Windows taskbar and Alt+Tab, X11 taskbars. Places the running program
does not control (Finder, .exe file icon, Linux launchers, Wayland docks) use the
files generated by ``scripts/build_icons.py`` and the packaging in ``packaging/``.
"""

from __future__ import annotations

import logging
import sys
from functools import lru_cache
from pathlib import Path

from PySide6.QtCore import QBuffer, QByteArray, QIODevice, Qt
from PySide6.QtGui import QIcon, QImage, QPixmap

log = logging.getLogger(__name__)

LOGO_NAME = "logo.png"
# Windows groups taskbar buttons by this id; without it a source run shows python.exe's icon.
WINDOWS_APP_ID = "lilx.browser"
_ICON_SIZES = (16, 24, 32, 48, 64, 128, 256, 512)


def logo_path() -> Path | None:
    """Location of logo.png: bundled with a frozen build, or in the project root."""
    candidates: list[Path] = []
    bundle = getattr(sys, "_MEIPASS", None)  # PyInstaller's data directory
    if bundle:
        candidates.append(Path(bundle) / LOGO_NAME)
    candidates.append(Path(__file__).resolve().parent.parent / LOGO_NAME)  # source checkout
    return next((path for path in candidates if path.is_file()), None)


@lru_cache(maxsize=1)
def _logo_image() -> QImage | None:
    path = logo_path()
    image = QImage(str(path)) if path else QImage()
    if image.isNull():
        log.warning("%s not found or unreadable; using the built-in fallback icon", LOGO_NAME)
        return None
    return image


def app_icon() -> QIcon:
    """The lilx icon with pre-scaled sizes (sharper than letting Qt scale 1254 px on the fly)."""
    image = _logo_image()
    if image is None:
        from lilx.ui import icons  # fallback: the drawn "L" mark used before logo.png

        return icons.icon("lilx", "#7456e8", 64, 2.4)
    icon = QIcon()
    for size in _ICON_SIZES:
        icon.addPixmap(QPixmap.fromImage(image.scaled(
            size, size, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)))
    return icon


@lru_cache(maxsize=4)
def logo_png(size: int) -> bytes:
    """logo.png scaled to ``size`` px as PNG bytes (tab icon of the lilx:// pages)."""
    image = _logo_image()
    if image is None:
        return b""
    scaled = image.scaled(size, size, Qt.AspectRatioMode.KeepAspectRatio, Qt.TransformationMode.SmoothTransformation)
    data = QByteArray()
    buffer = QBuffer(data)
    buffer.open(QIODevice.OpenModeFlag.WriteOnly)
    scaled.save(buffer, "PNG")
    buffer.close()
    return bytes(data.data())


def prepare_platform() -> None:
    """Platform setup that must happen before the first window exists."""
    if sys.platform == "win32":
        try:
            import ctypes

            ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(WINDOWS_APP_ID)
        except (AttributeError, OSError) as exc:
            log.debug("Could not set the Windows AppUserModelID: %s", exc)
